#!/usr/bin/python

import sys
import json
import argparse


def main():

    parser = argparse.ArgumentParser()
    parser.add_argument("filename", nargs="?")
    args = parser.parse_args()

    lines=""
    if args.filename is None:
        lines=sys.stdin.readlines()
    else:
        with open(args.filename) as f:
            lines=f.readlines()

    data_list = []
    section = {}

    for line in lines:
        if (line == "\n"):
            if len(section) == 0:
                continue
            data_list.append(section)
            section = {}
            continue

        
        ls = line.split(":",1)
        if len(ls) == 2:
            lk = ls[0].lstrip().rstrip().strip()
            lv = ls[1].lstrip().rstrip().strip()

            section[lk] = lv

    print(json.dumps(data_list))


if __name__ == "__main__":
    main()
